import { z } from 'zod'
import { DailyBalanceResponseSchema } from './balance'
import { MealLogResponseSchema } from './meal-log'
import { PendingActionResponseSchema } from './pending-action'

// turnId generated by the client: retried turns are idempotent (RF-70e, §6.3)
export const TurnInputSchema = z.object({
  turnId: z.string().uuid(),
  text: z.string().min(1).max(2000),
  // ⛔ MAI IMPLEMENTATO, e non lo sarà: presupponeva un archivio di immagini
  // lato server, che RNF-07 vieta. Resta nello schema perché toglierlo è un
  // cambio di contratto, ma nessuno lo legge — la foto viaggia in `image`.
  imageId: z.string().uuid().nullish(),
  // RNF-07 «Le immagini non si conservano»: la foto viaggia COL TURNO, in
  // base64, va al modello e muore lì. Non c'è un id perché non c'è un posto da
  // cui rileggerla; l'unica traccia che resta è `message.had_image`, un booleano.
  //
  // ⚠️ Il tetto è qui e non solo nel body limit di Fastify: sforare il limite
  // del server dà un 413 senza envelope, cioè un errore che il client non sa
  // leggere. 700 000 caratteri ≈ 525 KB di JPEG, e il client ridimensiona
  // molto sotto — questo è la rete, non la misura.
  image: z.string().min(1).max(700_000).nullish(),
  conversationId: z.string().uuid().nullish(),
  // W5: lo slot che l'utente ha SCELTO toccando la riga-bersaglio, `null` se non
  // ne ha scelto nessuno. ⛔ Non è «lo slot della schermata»: quello è
  // `chosenSlot ?? proposedSlot`, e la seconda metà è una DEDUZIONE (D-035) che
  // il server rifà da sé dagli stessi dati. Mandarla sarebbe una terza sede
  // della stessa regola invece di una sola — per questo il campo si chiama
  // `chosenSlotId` e non `slotId`.
  chosenSlotId: z.string().uuid().nullish(),
})

// D-024: le voci da chiarire accodate dal turno viaggiano con l'esito, così il
// client può renderne la scelta come dato strutturato (i candidati stanno nel
// payload). Sta su `logged` e su `answer` perché un batch di sole voci ambigue
// non scrive niente e cade su `answer`; su `proposal` non serve, il batch non
// produce proposte.
const unresolved = { unresolved: z.array(PendingActionResponseSchema).nullish() }

// polymorphic result: the client renders the shape, it never decides (§6.3)
export const TurnResultSchema = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('logged'),
    entries: z.array(MealLogResponseSchema),
    balance: DailyBalanceResponseSchema.nullish(),
    ...unresolved,
  }),
  z.object({
    kind: z.literal('answer'),
    text: z.string(),
    citations: z.array(z.string()),
    ...unresolved,
  }),
  z.object({
    kind: z.literal('proposal'),
    actions: z.array(PendingActionResponseSchema),
  }),
  // D-031: lo slot dichiarato saltato su richiesta esplicita dell'utente. È un
  // esito **strutturato** e non una frase del modello: senza, il client
  // saprebbe cosa è successo solo leggendo il testo — che è ciò che D-021 ha
  // già pagato in C3, quando il modello taceva la coda
  z.object({
    kind: z.literal('skipped'),
    mealSlotId: z.string().uuid(),
    slotLabel: z.string(),
    date: z.string(),
    balance: DailyBalanceResponseSchema.nullish(),
  }),
])

export type TurnInput = z.infer<typeof TurnInputSchema>
export type TurnResult = z.infer<typeof TurnResultSchema>
