import { z } from 'zod'
import { DailyBalanceResponseSchema } from './balance'
import { MealLogResponseSchema } from './meal-log'
import { PendingActionResponseSchema } from './pending-action'

// turnId generated by the client: retried turns are idempotent (RF-70e, §6.3)
export const TurnInputSchema = z.object({
  turnId: z.string().uuid(),
  text: z.string().min(1).max(2000),
  imageId: z.string().uuid().nullish(),
  conversationId: z.string().uuid().nullish(),
})

// polymorphic result: the client renders the shape, it never decides (§6.3)
export const TurnResultSchema = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('logged'),
    entries: z.array(MealLogResponseSchema),
    balance: DailyBalanceResponseSchema.nullish(),
  }),
  z.object({
    kind: z.literal('answer'),
    text: z.string(),
    citations: z.array(z.string()),
  }),
  z.object({
    kind: z.literal('proposal'),
    actions: z.array(PendingActionResponseSchema),
  }),
])

export type TurnInput = z.infer<typeof TurnInputSchema>
export type TurnResult = z.infer<typeof TurnResultSchema>
